### ISSUE TITLE
log level filter

### ISSUE THREAD

**Issue by hashar** [firejune/clog#1]
Hello,

It would be great if we could select verbosity of our scripts, i.e. disable output for message below a given threshold. Some script could then add clog.debug() message everywhere which will not be shown by default.

debug
info
log
warn
error

Info should be the default level I think. We could then handle a --debug arguments to ask clog to also output the debug messages.

**Comment by firejune** [comment]
Wow! Great idea! thanks, hashar.

**Comment by firejune** [comment]
Applies to version 0.1.2.
